### Register user
POST http://localhost:8080/register
Content-Type:application/json

{
 "username": "adam12",
 "password1": "12345",
 "password2": "12345"
}

### Login user
POST http://localhost:8080/login
Content-Type:application/json

{
"username": "admin",
"password": "12345"
}

### Logout user
POST http://localhost:8080/logout
Content-Type:application/json

### Get user information
GET http://localhost:8080/user
Content-Type:application/json

### Get current rank for user
GET http://localhost:8080/rank

### Create BlogPost
POST http://localhost:8080/addnewpost
Content-Type:application/json

{
    "blogTitle" : "Test",
    "blogContentText": "Hallo, mein Text!",
    "imageUrl": "asd"
}